### ISSUE TITLE
Add callout block to 6.0.0 changelog about SiteTree autoscaffolding 

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/developer-docs#656] opened 2024-12-17 04:07 UTC
Because of the changes to autoscaffolding for SiteTree, users who upgrade to CMS 6 may suddenly have form fields appear that they do not want to, which may even contain sensitive data

## Acceptance criteria
- A callout block is added to the 6.0.0 changelog highlighting that SiteTree form fields may unintentionally show on upgrade

**Comment by GuySartorelli** [comment] 2024-12-17 04:44
Closing as a duplicate of https://github.com/silverstripe/developer-docs/issues/657 which has a bit more detail

**Closed as completed by GuySartorelli** 2024-12-17 04:44 UTC
