### ISSUE TITLE
Update docs from graphql 3 to graphql 4 compatability

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#62] opened 2022-08-09 22:54 UTC
There are several sections in the docs outside the explicit graphql section that refer to graphql, e.g. https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#expose-graphql-scaffolding

These currently are written with graphql 3 compatability. They should be updated for graphql 4 compatability.

## Acceptance criteria
- [x] All graphql v3 examples in the CMS 4 docs are updated
    - [x] to ensure they still actually work
    - [x] to _also_ include graphql v4 examples
- [x] All graphql v3 examples in the CMS 5 docs are removed (leaving the graphql v4 examples)
    - [x] There are no mentions of "graphql v4"

## OLD CMS 4 PRs
Once these are all merged, reassign to me so I can update the CMS 5 docs
- https://github.com/silverstripe/developer-docs/pull/184
- https://github.com/silverstripe/silverstripe-admin/pull/1473
- https://github.com/silverstripe/developer-docs/pull/187
- https://github.com/silverstripe/developer-docs/pull/197

## OLD CMS 5 PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1481

## CMS 4 PRs
Once these are all merged, reassign to me so I can update the CMS 5 docs and code if necessary
- https://github.com/silverstripe/developer-docs/pull/211
- https://github.com/silverstripe/developer-docs/pull/215
- https://github.com/silverstripe/silverstripe-admin/pull/1498

## CMS 5 PRs
- https://github.com/silverstripe/developer-docs/pull/196
- https://github.com/silverstripe/developer-docs/pull/247
- https://github.com/silverstripe/silverstripe-admin/pull/1500

**Comment by rafaeldsousa** [comment] 2022-08-09 23:04
Can confirm the above. 
While following the guide, could see that queries present variables in wrong casing and that the queries do not include namespaces when created, as suggested at the bottom of the docs. 
**E.g**
```
readOneMyVersionedObject(
    Versioning: {
      Mode: LATEST
    },
    ID: $id
  ) {
    ID
    Versions (limit: $limit, offset: $offset) {
      pageInfo {
        totalCount
      }
      edges {
        node {
          Version
          Author {
            FirstName
            Surname
          }
          Publisher {
            FirstName
            Surname
          }
          Published
          LiveVersion
          LatestDraftVersion
          LastEdited
        }
      }
    }
  }
```

Not the case anymore, no part of namespace is included in the queries name.
```
GraphQL scaffolding derives the names for the schema from the first part of the namespace and the classname, while in the Injector the database table name is used. So in the case of ...
you would have to use readOneFooMyVersionedObject, rollbackFooMyVersionedObject and ...
```

**Comment by maxime-rainville** [comment] 2023-03-05 21:36
Duplicate of https://github.com/silverstripe/developer-docs/issues/164

**Comment by GuySartorelli** [comment] 2023-03-13 21:17
Reopening as its own card, as it turns out this is a _lot_ of work on its own.

**Comment by GuySartorelli** [comment] 2023-03-24 00:20
Reopening - still have the cms5 changes to make.

**Comment by sabina-talipova** [comment] 2023-03-24 00:20
Accidentally closed it. 
@GuySartorelli, all PRs are merged. You can create a follow-up PR for CMS 5.

**Comment by GuySartorelli** [comment] 2023-03-27 22:08
The code changes I made in CMS 4 were reverted in https://github.com/silverstripe/silverstripe-admin/pull/1488 because they were causing asset-admin to stop working.
I'll need to revert the CMS 5 changes as well.

I'll need to revisit this and carefully check that everything still works as expected this time.

**Comment by sabina-talipova** [comment] 2023-04-17 04:25
@GuySartorelli PRs for CMS 4 have been merged and ticket is ready for your further changes for CMS 5

**Comment by sabina-talipova** [comment] 2023-04-20 22:28
All PRs are merged. Close.

**Closed as completed by sabina-talipova** 2023-04-20 22:28 UTC
Labels: type/docs
